const vocabList1 = [
    { es: "La maravilla", de: "Das Wunder" },
    { es: "La ruina", de: "Die Ruine" },
    { es: "La línea", de: "Die Linie, die Zeile" },
    { es: "El recuerdo", de: "Die Erinnerung" },
    { es: "Limitar con algo", de: "(an)grenzen an" },
    { es: "Parecerle a alguien", de: "Jdm erscheinen" },
    { es: "Pensar en algo", de: "An etwas denken" },
    { es: "La política", de: "Die Politik" },
    { es: "Relacionar algo/alguien con algo", de: "Etwas / jdn mit etwas verbinden" },
    { es: "Andino/-a", de: "Anden-" },
    { es: "La agencia", de: "Die Agentur, das Büro" },
    { es: "El inca", de: "Der Inka" },
    { es: "La inca", de: "Die Inka" },
    { es: "Reservar algo", de: "Etwas reservieren" },
    { es: "El imperio", de: "Das Reich, das Imperium" },
    { es: "Interesarle a alguien", de: "Jdn. Interessieren" },
    { es: "Ocupar algo", de: "Etwas einnehmen, etwas besetzen" },
    { es: "El turista", de: "Der Tourist" },
    { es: "La turista", de: "Die Touristin" },
    { es: "La parte", de: "Der Teil" },
    { es: "Actual", de: "aktuell" },
    { es: "Hoy en día", de: "heutzutage" },
    { es: "La razón", de: "Der Grund" },
    { es: "La momia", de: "Die Mumie" },
    { es: "La tumba", de: "Das Grab" },
    { es: "El quechua", de: "Das Quechua" },
    { es: "La mitología", de: "Die Mythologie" },
    { es: "La teoría", de: "Die Theorie" },
    { es: "La planta", de: "(hier) die Pflanze" },
    { es: "La religión", de: "Die Religion" },
    { es: "El dios", de: "Der Gott" },
    { es: "La diosa", de: "Die Göttin" },
    { es: "Adorar a alguien", de: "Jdn. vergöttern, verehren" },
    { es: "La lengua, el idioma", de: "Die Sprache" },
    { es: "El terremoto", de: "Das Erdbeben" },
    { es: "Estable", de: "Stabil" },
    { es: "El consejo", de: "Der Rat" },
    { es: "Existir", de: "Existieren" },
    { es: "El mercado laboral", de: "Der Arbeitsmarkt" },
    { es: "El campesino", de: "Der Landwirt" },
    { es: "La campesina", de: "Die Landwirtin" },
    { es: "Vender algo", de: "Etwas verkaufen" },
    { es: "Comprar algo", de: "Etwas kaufen" },
    { es: "Pobre", de: "arm" },
    { es: "Rico/-a", de: "(hier) reich" },
    { es: "La barba", de: "Der Bart" },
    { es: "El oro", de: "Das Gold" },
    { es: "La esmeralda", de: "Der Smaragd" },
    { es: "Hacia", de: "In Richtung auf, nach" },
    { es: "La plata", de: "Das Silber" },
    { es: "El esclavo", de: "Der Sklave" },
    { es: "La esclava", de: "Die Sklavin" },
    { es: "Soñar (-ue) con algo", de: "Von etwas träumen" },
    { es: "Antes", de: "Früher, vorher" },
    { es: "La flauta", de: "Die Flöte" },
    { es: "El hueso", de: "Der Knochen" },
    { es: "La papa", de: "Die Kartoffel" },
    { es: "En ese tiempo", de: "Damals, zu dieser Zeit" },
    { es: "Humano/-a", de: "Menschlich" },
    { es: "El nudo", de: "Der Knoten" },
    { es: "El caballo", de: "Das Pferd" },
    { es: "El puma", de: "Der Puma" },
    { es: "La rueda", de: "Das Rad" },
    { es: "Cultivar algo", de: "Etwas anbauen" },
    { es: "El tomate", de: "Die Tomate" },
    { es: "El maíz", de: "Der Mais" },
    { es: "Correr", de: "Rennen, laufen" },
    { es: "El mensaje", de: "Die Nachricht" },
    { es: "El lago", de: "Der See" },
    { es: "El noble", de: "Der Adlige" },
    { es: "La noble", de: "Die Adlige" },
    { es: "En cambio", de: "Dagegen, stattdessen" },
    { es: "Cuidar algo / a alguien", de: "Sich um etwas / um jemanden kümmern" },
    { es: "La educación", de: "Die Bildung" },
    { es: "La formación profesional", de: "Die Berufsausbildung" },
    { es: "El puente colgante", de: "Die Hängebrücke" },
    { es: "Entonces", de: "dann" },
    { es: "El conejo", de: "Das Kaninchen" },
    { es: "El conejo de Indias, el cuy", de: "Das Meerschweinchen" },
    { es: "De repente", de: "Plötzlich" },
    { es: "El acontecimiento", de: "Das Ereignis" },
    { es: "La llegada", de: "Die Ankunft" },
    { es: "Morir (-ue-u)", de: "sterben" },
    { es: "El descubrimiento", de: "Die Entdeckung" },
    { es: "Descubrir algo", de: "Etwas entdecken" },
    { es: "Esconder algo", de: "Etwas verstecken" }
];

const vocabList2 = [
    { es: "¿Cuánto tiempo...?", de: "Wie lange...?" },
    { es: "Contaminar", de: "Verschmutzen, verseuchen" },
    { es: "El peligro", de: "Die Gefahr" },
    { es: "El espionaje", de: "Die Spionage" },
    { es: "Documentar", de: "Dokumentieren, belegen" },
    { es: "Inesperado/-a", de: "Unerwartet" },
    { es: "¿Te gustaría...?", de: "Würde (es) dir gefallen...?" },
    { es: "Financiar", de: "Finanzieren" },
    { es: "A través de...", de: "Durch..." },
    { es: "El consulado", de: "Das Konsulat" },
    { es: "La Cámara de Comercio", de: "Die Handelskammer" },
    { es: "El enero", de: "Der Januar" },
    { es: "El febrero", de: "Der Februar" },
    { es: "El marzo", de: "Der März" },
    { es: "El abril", de: "Der April" },
    { es: "El mayo", de: "Der Mai" },
    { es: "El junio", de: "Der Juni" },
    { es: "El julio", de: "Der Juli" },
    { es: "El agosto", de: "Der August" },
    { es: "El septiembre", de: "Der September" },
    { es: "El octubre", de: "Der Oktober" },
    { es: "El noviembre", de: "Der November" },
    { es: "El diciembre", de: "Der Dezember" },
    { es: "Con la presente carta", de: "Mit diesem Brief" },
    { es: "Permitir algo a alguien", de: "Etwas jemandem erlauben" },
    { es: "El visitante", de: "Der Besucher" },
    { es: "La visitante", de: "Die Besucherin" },
    { es: "Aumentar", de: "Steigen" },
    { es: "Planear", de: "Planen" },
    { es: "El público", de: "Das Publikum, die Öffentlichkeit" },
    { es: "La construcción", de: "Der Bau, das Bauwesen" },
    { es: "La instalación", de: "Die Anlagen" },
    { es: "Estar en condiciones (de)", de: "Können, in der Lage sein" },
    { es: "Suministrar", de: "Liefern" },
    { es: "La colaboración", de: "Die Zusammenarbeit" },
    { es: "A largo plazo", de: "Langfristig" },
    { es: "Saludar", de: "(be)grüßen" },
    { es: "Atentamente", de: "Mit freundlichen Grüßen" },
    { es: "El adjunto", de: "Die angehängte Datei" },
    { es: "El asunto", de: "Der Betreff, die Angelegenheit" },
    { es: "La petición", de: "Die Anfrage, die Bitte" },
    { es: "Especializarse", de: "Sich spezialisieren" },
    { es: "La madera", de: "Das Holz" },
    { es: "Distinto/-a", de: "Verschieden" },
    { es: "A continuación", de: "Danach" },
    { es: "El acuerdo", de: "Die Vereinbarung" },
    { es: "Llegar a un acuerdo", de: "Eine Vereinbarung treffen" },
    { es: "Según", de: "Laut, gemäß" },
    { es: "Ponerse en contacto", de: "Kontakt aufnehmen" },
    { es: "Estar en contacto", de: "In Kontakt bleiben" },
    { es: "La tarjeta de débito", de: "Die EC Karte" },
    { es: "El dinero en efectivo", de: "Das Bargeld" },
    { es: "Chino/-a", de: "Chinesisch" },
    { es: "¡Me parece chino!", de: "Das kommt mir spanisch vor." },
    { es: "El significado", de: "Die Bedeutung" },
    { es: "Pagar en efectivo", de: "Bar bezahlen" },
    { es: "Pagar con tarjeta", de: "Mit der Karte bezahlen" },
    { es: "Concreto/-a", de: "Genau, konkret" },
    { es: "La costumbre", de: "Die Gewohnheit" },
    { es: "Faltar", de: "Fehlen, vermissen" },
    { es: "El compañero", de: "Der Kollege" },
    { es: "La compañera", de: "Die Kollegin" },
    { es: "La prisa", de: "Die Eile" },
    { es: "Tener prisa", de: "Es eilig haben" },
    { es: "Impaciente", de: "Ungeduldig" },
    { es: "Paciente", de: "Geduldig" },
    { es: "El edificio", de: "Das Gebäude" },
    { es: "La oficina", de: "Das Büro" },
    { es: "El proveedor", de: "Der Lieferant" },
    { es: "El turoperador", de: "Der Veranstalter (bei Reisen oder Messen)" },
    { es: "La feria de...", de: "Die ...-Messe" },
    { es: "El mueble", de: "Die Möbel" },
    { es: "El vehículo", de: "Das Fahrzeug" },
    { es: "Los alimentos", de: "Die Lebensmittel" }
];

let vocabData = vocabList1; // default fallback
