const vocabData = [
    { es: "La maravilla", de: "Das Wunder" },
    { es: "La ruina", de: "Die Ruine" },
    { es: "La línea", de: "Die Linie, die Zeile" },
    { es: "El recuerdo", de: "Die Erinnerung" },
    { es: "Limitar con algo", de: "(an)grenzen an" },
    { es: "Parecerle a alguien", de: "Jdm erscheinen" },
    { es: "Pensar (ie) en algo", de: "An etwas denken" },
    { es: "La política", de: "Die Politik" },
    { es: "Relacionar algo/alguien con algo", de: "Etwas / jdn mit etwas verbinden" },
    { es: "Andino/-a", de: "Anden-" },
    { es: "La agencia", de: "Die Agentur, das Büro" },
    { es: "El inca", de: "Der Inka" },
    { es: "La inca", de: "Die Inka" },
    { es: "Reservar algo", de: "Etwas reservieren" },
    { es: "El imperio", de: "Das Reich, das Imperium" },
    { es: "Interesarle a alguien", de: "Jdn. Interessieren" },
    { es: "Ocupar algo", de: "Etwas einnehmen, etwas besetzen" },
    { es: "El turista", de: "Der Tourist" },
    { es: "La turista", de: "Die Touristin" },
    { es: "La parte", de: "Der Teil" },
    { es: "Actual", de: "aktuell" },
    { es: "Hoy en día", de: "heutzutage" },
    { es: "La razón", de: "Der Grund" },
    { es: "La momia", de: "Die Mumie" },
    { es: "La tumba", de: "Das Grab" },
    { es: "El quechua", de: "Das Quechua" },
    { es: "La mitología", de: "Die Mythologie" },
    { es: "La teoría", de: "Die Theorie" },
    { es: "La planta", de: "(hier) die Pflanze" },
    { es: "La religión", de: "Die Religion" },
    { es: "El dios", de: "Der Gott" },
    { es: "La diosa", de: "Die Göttin" },
    { es: "Adorar a alguien", de: "Jdn. vergöttern, verehren" },
    { es: "La lengua, el idioma", de: "Die Sprache" },
    { es: "El terremoto", de: "Das Erdbeben" },
    { es: "Estable", de: "Stabil" },
    { es: "El consejo", de: "Der Rat" },
    { es: "Existir", de: "Existieren" },
    { es: "El mercado laboral", de: "Der Arbeitsmarkt" },
    { es: "El campesino", de: "Der Landwirt" },
    { es: "La campesina", de: "Die Landwirtin" },
    { es: "Vender algo", de: "Etwas verkaufen" },
    { es: "Comprar algo", de: "Etwas kaufen" },
    { es: "Pobre", de: "arm" },
    { es: "Rico/-a", de: "(hier) reich" },
    { es: "La barba", de: "Der Bart" },
    { es: "El oro", de: "Das Gold" },
    { es: "La esmeralda", de: "Der Smaragd" },
    { es: "Hacia", de: "In Richtung auf, nach" },
    { es: "La plata", de: "Das Silber" },
    { es: "El esclavo", de: "Der Sklave" },
    { es: "La esclava", de: "Die Sklavin" },
    { es: "Soñar (-ue) con algo", de: "Von etwas träumen" },
    { es: "Antes", de: "Früher, vorher" },
    { es: "La flauta", de: "Die Flöte" },
    { es: "El hueso", de: "Der Knochen" },
    { es: "La papa", de: "Die Kartoffel" },
    { es: "En ese tiempo", de: "Damals, zu dieser Zeit" },
    { es: "Humano/-a", de: "Menschlich" },
    { es: "El nudo", de: "Der Knoten" },
    { es: "El caballo", de: "Das Pferd" },
    { es: "El puma", de: "Der Puma" },
    { es: "La rueda", de: "Das Rad" },
    { es: "Cultivar algo", de: "Etwas anbauen" },
    { es: "El tomate", de: "Die Tomate" },
    { es: "El maíz", de: "Der Mais" },
    { es: "Correr", de: "Rennen, laufen" },
    { es: "El mensaje", de: "Die Nachricht" },
    { es: "El lago", de: "Der See" },
    { es: "El noble", de: "Der Adlige" },
    { es: "La noble", de: "Die Adlige" },
    { es: "En cambio", de: "Dagegen, stattdessen" },
    { es: "Cuidar algo / a alguien", de: "Sich um etwas / um jemanden kümmern" },
    { es: "La educación", de: "Die Bildung" },
    { es: "La formación profesional", de: "Die Berufsausbildung" },
    { es: "El puente colgante", de: "Die Hängebrücke" },
    { es: "Entonces", de: "dann" },
    { es: "El conejo", de: "Das Kaninchen" },
    { es: "El conejo de Indias, el cuy", de: "Das Meerschweinchen" },
    { es: "De repente", de: "Plötzlich" },
    { es: "El acontecimiento", de: "Das Ereignis" },
    { es: "La llegada", de: "Die Ankunft" },
    { es: "Morir (-ue-u)", de: "sterben" },
    { es: "El descubrimiento", de: "Die Entdeckung" },
    { es: "Descubrir algo", de: "Etwas entdecken" },
    { es: "Esconder algo", de: "Etwas verstecken" }
];
